### ISSUE TITLE
Make sure all files that leanbuild::bookdown_to_leanpub() needs are transferred via gha

### ISSUE THREAD

**Issue by cansavvy** [jhudsl/OTTR_Template#134]
Now that we have somewhat of an attack plan, we need to reconfigure again what files are being transferred from this repo to its [Leanpub correlate](https://github.com/jhudsl/DaSL_Course_Template_Bookdown) 

If leanbuild::bookdown_to_leanpub() is not to be run until after files are transferred, I think that means that these are the files that are needed: 
-  everything in the `docs/` folder
-  _bookdown.yml
-  all .bib files

And maybe the Rmds too? (This may depend on how some adds to the leanbuild package land: https://github.com/jhudsl/leanbuild/issues/6)

**Comment by carriewright11** [comment]
You need Rmds just for `leanbuild::bookdown_to_leanpub()` to run (at least currently - and this is also helpful for one of my scripts) . I just tested this, I had assumed docs were required since it was previously in the transfer action, but it looks like the docs/ files aren't actually required. These get generated by `leanbuild::bookdown_to_leanpub()`.

**Comment by carriewright11** [comment]
With some further testing I think we actually only need book.bib and not packages.bib. 

So overall we need: 

1.  all Rmd files
2. the _bookdown.yml file
3. the book.bib file

**Comment by cansavvy** [comment]
Took some troubleshooting that led to some other problems, but we got there: 
https://github.com/jhudsl/DaSL_Course_Template_Leanpub/pull/32
