### ISSUE TITLE
Is it better to only keep the assets file in `docs/`

### ISSUE THREAD

**Issue by cansavvy** [jhudsl/OTTR_Template#212]
Right now there are two `assets` folders that contain styling items for rendering. I thought (but believe I am incorrect now) that the `assets` directory and its contents were copied over to `docs/assets` upon rendering, but a recent glitched showed me it is not (#211). 

To eliminate confusion on this aspect, does it make sense to only keep the assets copy that is in docs? (and fix the links accordingly?)

@carriewright11 you understand more about bookdown than I do, what do you think? I looked at the `https://github.com/rstudio/bookdown-demo` and it doesn't have such a folder (for some reason I thought it did) so now I'm wondering if reorganizing makes sense.

**Comment by carriewright11** [comment]
I just tested this with an older repo.  Indeed it looks like some files (not all) in the assets dir get copied over when you preview the course.   Was the issue with the hero image? in my test dir,  doesn't seem fixed with copying the big-image.html over. Instead I fixed it by modifying the big-image.html only in the assets dir. It did not work to only modify it in the docs/assets dir (which I tried first). This makes me think we might need it outside docs.

**Comment by carriewright11** [comment]
But I see that the hero image appears fixed with the bookdown template when I pull the main branch. interesting...

**Comment by cansavvy** [comment]
Okay. Sounds like this needs further digging. Im just trying to make sure we have one main copy and don't end up losing track of a copy or have to change things multiple times.

I'll have to play around with this and see what makes sense and I'll write some guidance about it in the new styling section: https://github.com/jhudsl/DaSL_Course_Template_Bookdown/wiki/Customizing-style

On a related note, @carriewright11 you understand more about styling than I do so feel free to add guidance to that page.

**Comment by cansavvy** [comment]
I think the main problems with this have been addressed adequately for version 1.0. Turned out to mostly be a broken URL:  https://github.com/jhudsl/Documentation_and_Usability/pull/86 Will keep issue open but remove the before 1.0 label.
