### ISSUE TITLE
links to new tab

### ISSUE THREAD

**Issue by carriewright11** [jhudsl/OTTR_Template#227]
**Is your feature request related to a problem? Please describe.**
It would be nice if when users clicked on a reference it took them to a new tab so that they don't lose their place in the chapter.

**Describe the solution you'd like**
Users could click on a reference and a new tab would open. Then they could return to reading the course

**Describe alternatives you've considered**
perhaps we can modify leanbuild to add target="_blank" and rel="noreferrer noopener"

**Additional context**

**Comment by cansavvy** [comment]
Sounds like a great idea. I’ll take a look into it.

**Comment by cansavvy** [comment]
This doesn't work in Leanpub so that's what's kind of holding me up for implementing this currently.

**Comment by cansavvy** [comment]
Now that Leanpub is using our iframes, we can do `target="_blank"` and that works. So we should update guidance and the pandoc citations accordingly so links always have `target="_blank"`

**Comment by cansavvy** [comment]
This issue is now obsolete with the iframe thing.

**Comment by carriewright11** [comment]
I wonder if we want reference links to also go to a new tab? So not citation... but references. But yeah, this is already so much better! :)

**Comment by cansavvy** [comment]
Yes ideally we want all links to go to a new window. So I'll reopen this issue.

**Comment by kweav** [comment]
Is this still an issue that I should assign myself?

**Comment by carriewright11** [comment]
I think it is worth at least checking how references and citations are navigated :)

**Comment by kweav** [comment]
Testing some references in the AI course bookdowns, they don't open in a new tab. I know adding the attribute `{target="_blank"}` after the `[]()` link syntax works for Pandoc, but now trying to figure out how to make it so that all links have that without adding that attribute for every link manually. If I'm understanding what you wrote before, we can make this addition to something in leanbuild or add a function there that automatically adds this attribute to links? And I think leanbuild is now [`ottrpal`](https://github.com/jhudsl/ottrpal)?

**Comment by howardbaik** [comment]
Echoing @kweav : The references in the AI for Decision Makers don't open in a new tab. I'll look into this right now.

**Comment by howardbaik** [comment]
Potentially useful code I found on the Internet: https://yihui.org/en/2018/09/target-blank/#open-external-links-in-new-tabs-automatically

**Comment by howardbaik** [comment]
@kweav I'll take this issue and will work on a fix in this new branch I created from this issue: `227-links-to-new-tab`
