### ISSUE TITLE
docker instructions

### ISSUE THREAD

**Issue by carriewright11** [jhudsl/OTTR_Template#29]
- maybe add the link for getting a docker account
- maybe add a check that Docker installed - just running Docker
- possibly add note that they might need to update docker if they get an error (I did :P)
- add a note that it will take some time to pull the docker image
- after starting up the image with the docker run command,  I needed to run docker ps in a different terminal window (as it was still busy)
-  maybe type use username :rstudio password: what you just created to make it even more clear or maybe even an image of the sign in with rstudio typed as the username - I missed it for a second

Also, I have some images/descriptions about docker in general if you want to link out to this tutorial or use some of the material (https://github.com/carriewright11/covid_epi) for users who aren't familiar with Docker (not necessary - just a thought)

**Comment by cansavvy** [comment]
This is great feedback! Thanks @carriewright11 I will file a PR to address these things!

**Comment by cansavvy** [comment]
> Also, I have some images/descriptions about docker in general if you want to link out to this tutorial or use some of the material (https://github.com/carriewright11/covid_epi) for users who aren't familiar with Docker (not necessary - just a thought)

Docker just did a bunch of updates (or it seems that way from what my Docker looks like) so some of these images are either from an older version or specific to what computer you are using. 😢 

I can definitely add some screenshots though if that'd be helpful.

**Comment by carriewright11** [comment]
yes, I think the images for pricing etc are a bit different - but the descriptions about what Docker is in general are probably still applicable. some if it is in the https://carriewright11.github.io/covid_epi/#accessing-the-required-r-and-python-tools-on-your-computer section  which shows possible differences in commands across operating systems .. might want to think about different shells - might be good to suggest using RStudio's terminal

**Comment by cansavvy** [comment]
Cool! I'll take a look and file another PR.

**Comment by KatherineCox** [comment]
As someone who's never used Docker before (or at least, not locally and not from the command line), I had a bit of trouble following the Docker commands and knowing what I should be replacing with my own information (e.g. should I use `jhudsl/itcr_course_template` or something of my own?)

@carriewright11 's [explanations](https://github.com/carriewright11/covid_epi) were helpful

- clarified that it was pulling the `itcr_course_template` image from Docker Hub (rather than having anything to do with the GitHub repo) and copying it to my local collection of Docker images
- warned that it could take a while to pull the image
- clarified that `docker run` was looking at my local collection of Docker images (rather than having anything to do with the GitHub repo)

I also didn't understand how my repo files were being mounted.

I think these are all obvious if you've used Docker before, but were confusing to me as a newbie - essentially where is Docker looking for things - when is it going to Docker Hub, when is it looking at my repo, when is it looking somewhere else on my local computer, when do I need a Docker file in my repo, how do I make the files from my repo accessible to the container...

Not necessarily your job to explain Docker, but maybe a bit of expanded explanation to clarify what pieces of the commands are doing and what I should edit, e.g.:

Particularly for courses that involve running example code, it's recommended that you use a Docker image for development to maintain software version consistency across course developers. **A Docker image is similar to a virtual machine - it contains preinstalled software in a preconfigured environment.  Docker images can be downloaded from DockerHub, or you can create your own.  We have created the `itcr_course_template` image as a starting point; you can download it from `jhudsl/itcr_course_template` on DockerHub using the `docker pull` command.**

...

To pull the docker image associated with this template, you can run this command in your command line.  **This pulls the itcr_course_template image from Docker Hub and copies it to your computer.  It will be placed in your local collection of Docker images, managed by Docker (not in your `pwd`).  This may take a while.**

...

To use the Docker image associated with the course template, first navigate to the the top of this GitHub repository.  This ensures that the files in this repository will be available. Now you can start up the Docker container using the command below.  **This runs your local copy of the `itcr_course_template` image (which you downloaded from DockerHub).  The option `-v $PWD:/home/rstudio` mounts `pwd` (this repo) and makes it available at `/home/rstudio` within the container.** Replace `password` with something else of your choosing.

**Comment by cansavvy** [comment]
@KatherineCox This is great! Thanks for these insights! I'll incorporate more this into the getting_started.md!
