### ISSUE TITLE
What's the recommended workflow for using the docx way of writing and editing?

### ISSUE THREAD

**Issue by cansavvy** [jhudsl/OTTR_Template#306]
How should this docx be used? I think it makes sense to keep it on Google Drive and I think if we borrow mechanics from leanbuild, this is very doable, but we should discuss what this workflow should look like. We don't want peoples edits in the docx to get overwritten. 

Also what's the best way to transfer edits from a docx to the Rmds?

> We might want to think about how we advise this docx is used though. We could probably be fancy and have changes to the docx uploaded to Google Drive, but I'd also hate for people's edits to get overwritten at any point, so I'm not sure what's the ideal workflow for this. I'll make an issue for us to discuss this.

_Originally posted by @cansavvy in https://github.com/jhudsl/DaSL_Course_Template_Bookdown/issues/303#issuecomment-958998353_

**Comment by avahoffman** [comment]
I agree overwriting is a problem. Maybe by default it can be read-only, forcing users to make their own copy?

I didn't mess around with Google Drive too much, since then we get into the weeds of authentication, where the file lives, etc. It'll just take a bit more work.

I am envisioning the docx as more of a convenience feature, with individual instructors being able to download the book as a docx should they decide to. The reasoning here is because _many of the instructors aren't comfortable forking / editing their own repo_. However they still need to be able to tailor the content to their individual class. I imagine this appearing as a link to the docx on the bottom of the introduction and perhaps the bottom of the chapters. It could also be a drive link.

_I think we strictly do not want conversion back to .Rmd._ The reasoning here is that every instructor will have different minor edits for their own use that aren't relevant to everyone else. If they want to have more control over the html, I think we want them to fork the repo. 

There's also the question, how do we want the docx to be formatted? Apparently we can get creative 😃

**Comment by carriewright11** [comment]
That makes sense. I understand better now how people might be using the repos. Happy to help with formatting :)

**Comment by carriewright11** [comment]
This might be helpful: https://ardata-fr.github.io/officeverse/office-documents-generation.html#templates

**Comment by cansavvy** [comment]
Thanks for the context info, @avahoffman 

> I didn't mess around with Google Drive too much, since then we get into the weeds of authentication, where the file lives, etc. It'll just take a bit more work.

I normally would agree, but muschellij2 did a lot of the work for these kinds of entanglements on leanbuild, so we should be able to borrow from there. 

> I think we strictly do not want conversion back to .Rmd. 

Totally agree, I think this is a whole tangled world we don't even want to get into. 

Based on what you are saying then, I could see a situation for making a read-only google doc version that you someone could make comments on. And should they want to, they could make a copy and do as they will with that copy. Does this make sense? Main key would be to make sure comments don't get delete if there's an update. And that I'd have to look into.

**Comment by avahoffman** [comment]
Sounds good! Perhaps instead of comments we should just make it clear that users should submit an issue (which is fairly non-technical)? I imagine getting comments to persist is tricky.

**Comment by cansavvy** [comment]
> Sounds good! Perhaps instead of comments we should just make it clear that users should submit an issue (which is fairly non-technical)? I imagine getting comments to persist is tricky.

Yes, for general comments, I think an issue is best, but I could see situations in which people want to make line-by-line comments and this is where Google Docs would really come in handy

**Comment by cansavvy** [comment]
Meh. After doing a quick look around at some tools and solutions. I think manual upload to google drive and commenting is the best. That way people know exactly what they are commenting on. Keep it simple.

**Comment by avahoffman** [comment]
+1 Meh. So keep as is with docx download? The user then decides where to take it from there?

**Comment by cansavvy** [comment]
I think so. We can add something in the Wiki section that describes some suggestions on how to use it.

**Comment by avahoffman** [comment]
Sounds good. I think we might also want to show users how to take it out (I think it adds considerable build time for large repos).

I'm happy to add to the wiki :) #312

**Comment by cansavvy** [comment]
It looks like #312 addresses the last of this issue so I think we can close this?
