### ISSUE TITLE
Convert to dasl_course_template_bookdown

### ISSUE THREAD

**Issue by jtleek** [jhudsl/OTTR_Template#35]
At some point it would be good to create a more generic repo from this (if you haven't already and I missed it!) called dasl_course_template_bookdown that uses the more generic slide template etc @carriewright11 @cansavvy

**Comment by carriewright11** [comment]
Yes, will do after we get this one is more finalized.

**Comment by cansavvy** [comment]
I think this can be done, except for two issues that are potentially blocking it: #66 and #49 

However if we don't think we need code output images to be refreshed with google slides then #49 is not blocking. But I should add instructions in regards to #66 before starting this issue.

**Comment by cansavvy** [comment]
I figure we shouldn't wait for #49 to get resolved because I don't know how long that will take. We can just transfer over changes once its figured out. 

But the more general repo template is now created and I'm in the process of de-ITCR-ing it: https://github.com/jhudsl/DaSL_Course_Template_Bookdown/pull/1

**Comment by cansavvy** [comment]
This issue is generally done! The more specific items will be tracked on the new repo: https://github.com/jhudsl/DaSL_Course_Template_Bookdown
