### ISSUE TITLE
More Testing!

### ISSUE THREAD

**Issue by cansavvy** [jhudsl/OTTR_Template#41]
### Summary 

I wrote a lot of things in `getting_started.md`. I think they make sense, but we need other people to try them! 

Whatever isn't clear we can document here and I will address and add clarity. 

@carriewright11 I think was going to do some poking around and see if the github actions, spell check, styler and etc make sense and also whether any settings need to be tweaked.

**Comment by carriewright11** [comment]
sounds good - I am actually working on checking it right now :)

**Comment by carriewright11** [comment]
Looks great! - Some little suggestions - I made these check boxes for you but no need to do them if you decide to do something else:

**Set up branches section**
- [ ] since it is the first rule would be better to say "click `Add rule`" instead of `Add new rule`
- [ ] need to say to check the `Require status checks to pass before merging` then say to check the `Require branches to be up to date before merging` underneath
- [ ] click create and save changes to finish out the set up branches section
- [ ] the part about check_urls and style_n_check was a bit confusing - maybe say something like :  After the first pull request, a couple of checks will automatically happen. You can require them to pass before merging pull requests by returning here and selecting them - they are `url_check` and  `style-n-check` they will check that the urls work and that the code is styled using the `stylr` package and that the spelling is correct using the `spelling` package respectively.

**Setting up the Docker image**
- [ ] maybe add more explanation about what Docker is and why this is helpful

**Citations section**
- [ ] maybe add that people can use programs like Zotero/endnote to export  a `.bib` file to use as a `references.bib` file. 
- [ ] it is a bit confusing to copy paste to the `references.bib` file since it doesn't exist yet

**Comment by carriewright11** [comment]
I'm trying out spelling errors etc to see how that works

**Comment by carriewright11** [comment]
Spelling checks all worked as anticipated and your directions were very clear about how to update the dictionary etc. Now working on style.

**Comment by carriewright11** [comment]
Stylr and docker changes all worked as anticipated and documentation was very clear. Maybe change the part about checking urls to say that you add it to the `blacklist`.

**Comment by KatherineCox** [comment]
- Thanks very much for the advice on repository settings, I wouldn't have know to do this!
	- we don't require build-all?
- Should LICENSE be updated to CC-BY, or should we have instructions that course developers should update the LICENSE (and leave the template under MIT)?
- Looks like images should be placed in `resources/images/`?  Perhaps state this explicitly under ### Adding Images and Graphics
- Link to https://happygitwithr.com/ for people who aren't familiar/comfortable with Git and GitHub?
- What does the repo option in _bookdown.yml do, and what happens if I forget to change it?  If this is important to set upfront, it'd be good to highlight it in the instructions.

**Comment by cansavvy** [comment]
@KatherineCox and @carriewright11 thanks for this excellent feedback! I'm going to file a PR sometime today and attempt to address these ideas and comments!

**Comment by cansavvy** [comment]
> What does the repo option in _bookdown.yml do, and what happens if I forget to change it? If this is important to set upfront, it'd be good to highlight it in the instructions.

I'm actually not sure, @carriewright11 do you know? 

> Should LICENSE be updated to CC-BY, or should we have instructions that course developers should update the LICENSE (and leave the template under MIT)?

Do you also have insights on this^, @carriewright11?

**Comment by carriewright11** [comment]
Yeah I think it is fine to update to CC-BY - I had made it MIT in earlier versions just because it is my default. But we can double check with Jeff
