### ISSUE TITLE
add more words to dictionary that are just part of the template

### ISSUE THREAD

**Issue by carriewright11** [jhudsl/OTTR_Template#732]
I noticed that words like names of people in the default about are not in the dictionary and get flagged as misspellings which could be annoying for users. I think there are some other words as well.

**Comment by kweav** [comment]
I created a fresh test repository from the template and made a token change to the README in order to create a branch and open a PR. In that PR, I can verify that all checks ran without error. Therefore, I think the changes made to the dictionary file (in [this commit](https://github.com/jhudsl/OTTR_Template/commit/993b6ac9cfd02ace188c78c65b1d8d85ec741732)) together with including exclude files (in [this commit](https://github.com/jhudsl/OTTR_Template/commit/d94956a87a3980f83748b3a9973ab8ab623dfd51)) that this issue can be closed? 

I know the README is one of the excluded files from the checks, but my reading of this issue is that we don't want users to have to deal with spelling errors right away for words that are just in the template, so I just wanted to run the check on a fresh template.
